Use Github actions instead of Travis CI (#278)
api-platform/schema-generator pull request #292
Opened 2021-01-30 18:25 UTC by johnkrovitch

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tickets       | fixes #278 
| License       | MIT
| Doc PR        |

Hi,

the goal of this PR is to move the CI from Travis CI to Github Actions. It aims to have the same behavior than Travis (#278).

Two worklows has been created :
- ci.yaml : build the project, run the tests and the cs-fixer
- release.yaml : upload the schema.phar asset when a new release is created

Note :
- I am not sure why the php-cs-fixer and phpstan analye were only enabled for php 8.0, so it is now enabled for php 7.4 (but it can be easily reverted)

2021-02-02 15:05 UTC, dunglas requested changes
Thanks for handling this!! I made a few comments but it looks very promising.

2021-02-02 15:05 UTC, dunglas commented on .github/workflows/ci.yml
> +          vendor/bin/php-cs-fixer fix --dry-run --diff --no-ansi
You can use `php-cs-fixer fix --dry-run --format=checkstyle | cs2pr` to annotate the PR directly in the GitHub UI! (`cs2pr` must be added to the tools installed by setup-php).

2021-02-02 15:05 UTC, dunglas commented on .github/workflows/release.yml
> +      extensions: json, xdebug
```suggestion
      extensions: json
```

2021-02-02 15:05 UTC, dunglas commented on .github/workflows/release.yml
> +      - uses: php-actions/composer@v5
Can't we use `setup-php` instead to uniformize?

2021-02-02 15:05 UTC, dunglas commented on .github/workflows/release.yml
> +  release:
Shouldn't this pipeline run on tags instead of on releases (because it creates a release, so it will never be triggered).

2021-02-02 15:05 UTC, dunglas commented on .github/workflows/release.yml
> +    env:
Some lines look missing:

```
      - name: Setup PHP with extensions
        uses: shivammathur/setup-php@v2 
```

2021-02-04 21:15 UTC, johnkrovitch commented on .github/workflows/ci.yml
> +      extensions: json, xdebug
Done

2021-02-04 21:15 UTC, johnkrovitch commented on .github/workflows/ci.yml
> +          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
Done

2021-02-04 21:18 UTC, johnkrovitch commented on .github/workflows/ci.yml
> +      - name: Install project for PHP 8.0
Yes I agree, I just copied this from the Travis configuration

2021-02-04 21:19 UTC, johnkrovitch commented on .github/workflows/ci.yml
> +          vendor/bin/php-cs-fixer fix --dry-run --diff --no-ansi
Done

2021-02-04 21:20 UTC, johnkrovitch commented on .github/workflows/release.yml
> +  release:
Actually the workflow just upload a build asset when a release is created, it does not create release. But it can be changed.

2021-02-04 21:22 UTC, johnkrovitch commented
Changes done. Do you want that the release workflow create the release or just upload release asset ?

2021-02-04 21:51 UTC, dunglas commented
If it can create the release when a tag is created it's even better

2021-02-08 21:52 UTC, johnkrovitch commented
The release workflow has been changed : it creates now a new release when a tag is pushed, and still upload release assets (schema.phar).

I'm not sure what to do about the changelog, should it be generated automatically or manually by a maintainer ?

2021-04-29 21:06 UTC, merged

2021-04-29 21:07 UTC, dunglas commented
Thanks @johnkrovitch! Regarding the changelog, we currently handle it manually.