Upgrade schema.org URLs to https
api-platform/schema-generator pull request #329
Opened 2021-05-02 16:26 UTC by ibousfiha

| Q             | A
| ------------- | ---
| Branch?       | master 
| Tickets       |  
| License       | MIT
| Doc PR        | api-platform/docs#... 
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
<!--

Hi, this is a simple upgrade of schema.org URLs to https

2021-05-02 18:37 UTC, dunglas commented
The schema.org namespace is `http://`, not `https://`. This cannot be merged, this would break interoperability with all other RDF tools aware of Schema.org.

See https://stackoverflow.com/a/27112323

2021-05-02 18:43 UTC, dunglas commented
Actually, it looks like Schema.org is in the process of supporting both schemes: https://github.com/schemaorg/schemaorg/issues/2853

So we may switch, but we must double-check that it doesn't break anything relying on Schema.org on other repositories (core and admin especially).

2021-05-03 15:04 UTC, ibousfiha commented
Sure, please let me know if I should correct anything else or to do further tests.

2021-05-21 14:00 UTC, UnseenBook requested changes
This week I tried moving to https://schema.org as well, but I encountered a problem with the cardinality config. In the `v1.owl` file all links are to http://schema.org and I couldn't find an alternative.

2021-10-20 10:10 UTC, ibousfiha commented
Needs to check phpunit tests

2021-11-17 16:19 UTC, alanpoulain commented on src/TypesGeneratorConfiguration.php
>      public const GOOD_RELATIONS_URI = 'https://archive.org/services/purl/goodrelations/v1.owl';
@dunglas what do you think of having the HTTPS version hosted on the API Platform website?

2021-11-17 17:00 UTC, merged

2021-11-17 17:00 UTC, alanpoulain commented
I've fixed the tests, thank you @ibousfiha!