operation openapi attribute support
api-platform/schema-generator pull request #430
Opened 2024-09-20 07:01 UTC by PawelSuwinski

Operation `openapiContext` attribute is deprecated and will be removed in Api Platform Core 4.0.
This PR allows transparent migration to `openapi` attribute ( `s/openapiContext:/openapi:/` should be enough).

 Resolve #427

2024-09-20 08:40 UTC, PawelSuwinski commented
About failed checks: 

1. Does it still have to cover unsupported php versions 7.4 and 8.0? 

Please let me know, to not to put unnecessary work into it making backward compatibility  (its mostly about  method named arguments). After all it is for Api Platform Core 4.0.

2. php 8.3 check fail is weird, I have all green on my workstation (?).

2025-02-11 07:44 UTC, PawelSuwinski commented
RFR, WDYT @dunglas ?

2025-02-27 09:30 UTC, PawelSuwinski commented
Hi, @soyuka/ @dunglas can we merge this or please can you give some feedback/ review?   Checks solved, all green.

2025-02-27 10:44 UTC, dunglas requested changes
Hey, sorry for the time we took to review.

The approach looks good to me overall, but I left some comments to make the code more readable.

2025-02-27 10:44 UTC, dunglas commented on src/AttributeGenerator/ApiPlatformCoreAttributeGenerator.php
> +                            function (?string $type) use ($class) {
```suggestion
                            function (?string $type): void use ($class) {
```

2025-02-27 10:44 UTC, dunglas commented on src/AttributeGenerator/ApiPlatformCoreAttributeGenerator.php
> +                    }
```suggestion
                    }

```

2025-02-27 10:44 UTC, dunglas commented on src/AttributeGenerator/ApiPlatformCoreAttributeGenerator.php
> +                (new \ReflectionClass($type))->getConstructor()?->getParameters() ?? [],
Maybe could we should we rewrite this code without using `array_reduce` and of ternary to make it more readable?

2025-02-27 10:44 UTC, dunglas commented on src/AttributeGenerator/ApiPlatformCoreAttributeGenerator.php
> +                static fn (array $types, \ReflectionParameter $refl) => $types + [
```suggestion
                static fn (array $types, \ReflectionParameter $refl): array => $types + [
```

2025-02-27 10:44 UTC, dunglas commented on src/AttributeGenerator/ApiPlatformCoreAttributeGenerator.php
> +                    $refl->getName() => $refl->getType() instanceof \ReflectionNamedType
`$refl->getType()` could be stored in a variable to prevent calling the function multiple times and increase readability.

2025-02-27 10:44 UTC, dunglas commented on src/AttributeGenerator/ApiPlatformCoreAttributeGenerator.php
> +            if (null !== $type && \is_array($parameter)) {
You could invert the condition and use `continue` instead to make the code more readable.

2025-02-27 10:44 UTC, dunglas commented on src/AttributeGenerator/ApiPlatformCoreAttributeGenerator.php
> +                            ? [$parameter]
Please prevent nested ternaries. Don't hesitate to use a plain loop instead of array functions to make the code more easy to read.

2025-02-27 10:44 UTC, dunglas commented on src/AttributeGenerator/ApiPlatformCoreAttributeGenerator.php
> +                        static fn (array $values) => Literal::new(
```suggestion
                        static fn (array $values): Literal => Literal::new(
```

2025-02-27 15:02 UTC, PawelSuwinski commented
All fixed, thanks for PR.

2025-09-03 11:18 UTC, PawelSuwinski commented
Hi @dunglas,  can we merge this then?

2026-01-28 20:03 UTC, merged